
INSERT INTO ATTACHMENT_LIST (ATTACHMENT_LIST_ID) VALUES (-752);
INSERT INTO ATTACHMENT_LIST (ATTACHMENT_LIST_ID) VALUES (-753);
INSERT INTO ATTACHMENT_LIST (ATTACHMENT_LIST_ID) VALUES (-754);
INSERT INTO ATTACHMENT_LIST (ATTACHMENT_LIST_ID) VALUES (-755);
INSERT INTO RESOURCE (RES_ID, NAME, DESCRIPTION, CREATED_BY, CREATED_ON, ATTACHMENT_LIST_ID) VALUES (-147, 'res1', NULL, 'admin', '2017-01-01', -752);
INSERT INTO RESOURCE (RES_ID, NAME, DESCRIPTION, CREATED_BY, CREATED_ON, ATTACHMENT_LIST_ID) VALUES (-789, 'res2', NULL, 'admin', '2018-01-01', -753);
INSERT INTO RESOURCE (RES_ID, NAME, DESCRIPTION, CREATED_BY, CREATED_ON, ATTACHMENT_LIST_ID) VALUES (-159, 'res3', '<p>My D&scription</p>', 'admin', '2019-01-01', -754);
INSERT INTO RESOURCE (RES_ID, NAME, DESCRIPTION, CREATED_BY, CREATED_ON, ATTACHMENT_LIST_ID) VALUES (-357, 'res4', 'null', 'admin', '2020-01-01', -755);
