INSERT INTO THIRD_PARTY_SERVER (SERVER_ID, NAME, URL, AUTH_POLICY, AUTH_PROTOCOL) VALUES (1, 'GitHub', 'https://github.com', 'APP_LEVEL', 'BASIC_AUTH');
INSERT INTO SCM_SERVER (SERVER_ID, KIND) VALUES (1, 'git');

INSERT INTO SCM_REPOSITORY (SCM_REPOSITORY_ID, SERVER_ID, NAME, REPOSITORY_PATH, WORKING_BRANCH) VALUES (-48, 1, 'Repository-1', 'home/test/repo1', 'master');
INSERT INTO SCM_REPOSITORY (SCM_REPOSITORY_ID, SERVER_ID, NAME, REPOSITORY_PATH, WORKING_BRANCH) VALUES (-32, 1, 'Repository-2', 'home/test/repo2', 'master');
INSERT INTO SCM_REPOSITORY (SCM_REPOSITORY_ID, SERVER_ID, NAME, REPOSITORY_PATH, WORKING_BRANCH) VALUES (-16, 1, 'Repository-3', 'home/test/repo3', 'master');
