
Insert into ATTACHMENT_LIST(ATTACHMENT_LIST_ID) values
(762);
Insert into ISSUE_LIST(ISSUE_LIST_ID) values
(188);

INSERT INTO EXECUTION (EXECUTION_ID, TCLN_ID, CREATED_BY, CREATED_ON, LAST_MODIFIED_BY, LAST_MODIFIED_ON, DESCRIPTION, NAME, EXECUTION_MODE, EXECUTION_STATUS, LAST_EXECUTED_BY, LAST_EXECUTED_ON, ATTACHMENT_LIST_ID, ISSUE_LIST_ID, PREREQUISITE, TC_NATURE, TC_TYPE, TC_STATUS, IMPORTANCE, REFERENCE, TC_DESCRIPTION) VALUES
(47, NULL, 'guest_tpl', '2011-06-21 08:40:32', 'guest_tpl', '2011-06-21 08:41:00', NULL, '111_Connection with the default user', 'MANUAL', 'FAILURE', 'guest_tpl', '2011-06-21 08:41:00', 762, 188, '', '', '', '', '', NULL, NULL);