
-- Feature 7183 when ordered lists have duplicate key for order column


-- create an attachment list. All will refer to it.

INSERT INTO ATTACHMENT_LIST (ATTACHMENT_LIST_ID) VALUES
(-907);

-- create a project

INSERT INTO TEST_CASE_LIBRARY (TCL_ID, ATTACHMENT_LIST_ID) VALUES (-25, -907);
INSERT INTO REQUIREMENT_LIBRARY (RL_ID, ATTACHMENT_LIST_ID) VALUES (-25, -907);
INSERT INTO CAMPAIGN_LIBRARY (CL_ID, ATTACHMENT_LIST_ID) VALUES (-25, -907);
INSERT INTO CUSTOM_REPORT_LIBRARY (CRL_ID, ATTACHMENT_LIST_ID) VALUES (-25, -907);

INSERT INTO PROJECT (PROJECT_ID, NAME, CREATED_BY, CREATED_ON, ATTACHMENT_LIST_ID, REQ_CATEGORIES_LIST, TC_NATURES_LIST,
TC_TYPES_LIST, TCL_ID, CL_ID, RL_ID, CRL_ID) VALUES
(-25, 'project-test', 'admin', '2016-06-29', -907, -1, -2, -3, -25, -25, -25, -25);

-- create test cases

INSERT INTO TEST_CASE_LIBRARY_NODE (TCLN_ID, NAME, CREATED_BY, CREATED_ON, PROJECT_ID, ATTACHMENT_LIST_ID) VALUES
(-121, 'tc-test', 'admin', '2018-03-18', -25, -907),
(-122, 'tc-test-2', 'admin', '2018-03-18', -25, -907);

INSERT INTO TEST_CASE (TCLN_ID, VERSION, TC_NATURE, TC_TYPE, PREREQUISITE) VALUES
(-121, 1, -12, -20, ''),
(-122, 1, -12, -20, '');

-- and the steps

insert into TEST_STEP (TEST_STEP_ID) VALUES
(-15), (-16), (-17), (-18), (-19);

INSERT INTO TEST_CASE_STEPS (TEST_CASE_ID, STEP_ID, STEP_ORDER) VALUES
(-121, -15, 0),
(-121, -16, 1),
(-121, -17, 1),
(-122, -18, 0),
(-121, -19, 2);

