INSERT INTO TEST_CASE_LIBRARY (TCL_ID, ATTACHMENT_LIST_ID) VALUES (3, 907);
INSERT INTO REQUIREMENT_LIBRARY (RL_ID, ATTACHMENT_LIST_ID) VALUES (3, 907);
INSERT INTO CAMPAIGN_LIBRARY (CL_ID, ATTACHMENT_LIST_ID) VALUES (3, 907);
INSERT INTO CUSTOM_REPORT_LIBRARY (CRL_ID, ATTACHMENT_LIST_ID) VALUES (3, 907);

INSERT INTO PROJECT(PROJECT_ID, NAME, CREATED_BY, CREATED_ON, ATTACHMENT_LIST_ID, REQ_CATEGORIES_LIST, TC_NATURES_LIST,
                    TC_TYPES_LIST, TCL_ID, CL_ID, RL_ID, CRL_ID) VALUES
(3, 'project-test-3', 'admin', '2016-06-29', 907, -1, -2, -3, 3, 3, 3, 3);


INSERT INTO TEST_AUTOMATION_SERVER(SERVER_ID, BASE_URL, LOGIN, PASSWORD, KIND, NAME, CREATED_ON) VALUES
(3, 'http://localhost:9080/jenkins', 'bob', 'bob', 'jenkins', 'bob', '2018-12-18 15:10:00');

INSERT INTO TEST_AUTOMATION_PROJECT(TA_PROJECT_ID, TM_PROJECT_ID, SERVER_ID, LABEL, REMOTE_NAME, EXECUTION_ENVIRONMENTS) VALUES
(3, 3, 3, 'bob', 'bob', 'bob');

INSERT INTO AUTOMATED_TEST(TEST_ID, NAME, PROJECT_ID) VALUES
(3, 'name.ta', 3);

INSERT INTO TEST_CASE_LIBRARY_NODE (TCLN_ID, NAME, CREATED_BY, CREATED_ON, PROJECT_ID, ATTACHMENT_LIST_ID) VALUES
(3, 'tc-test', 'admin', '2018-03-18', 3, 907),
(4, 'tc-test-2', 'admin', '2018-03-18', 3, 907),
(5, 'tc-test-3', 'admin', '2018-03-18', 3, 907);



INSERT INTO TEST_CASE (TCLN_ID, VERSION, TC_NATURE, TC_TYPE, PREREQUISITE, TA_TEST) VALUES
(3, 1, -12, -20, '', 3),
(4, 1, -12, -20, '', NULL),
(5, 1, -12, -20, '', NULL);
